/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { About } from './models/about';
export { AboutImages } from './models/about-images';
export { AcademicsPage } from './models/academics-page';
export { Achievement } from './models/achievement';
export { Admission } from './models/admission';
export { AdmissionInfo } from './models/admission-info';
export { AdmissionRequirement } from './models/admission-requirement';
export { Button } from './models/button';
export { Department } from './models/department';
export { DepartmentInfo } from './models/department-info';
export { Faculty } from './models/faculty';
export { Footer } from './models/footer';
export { Header } from './models/header';
export { Home } from './models/home';
export { HtmlTable } from './models/html-table';
export { Masters } from './models/masters';
export { Menu } from './models/menu';
export { MenuLinks } from './models/menu-links';
export { MissionAndValues } from './models/mission-and-values';
export { MoreLink } from './models/more-link';
export { QuickButtons } from './models/quick-buttons';
export { Scholarship } from './models/scholarship';
export { ScholarshipPage } from './models/scholarship-page';
export { School } from './models/school';
export { SocialMediaLinks } from './models/social-media-links';
export { TableData } from './models/table-data';
export { TuitionPage } from './models/tuition-page';
export { Undergraduate } from './models/undergraduate';
export { UsersRequest } from './models/users-request';
