/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AboutImages } from '../models/about-images';
import { Achievement } from '../models/achievement';
import { MissionAndValues } from '../models/mission-and-values';
export interface About {
  achievementImageUrl?: string;
  achievements?: Array<Achievement>;
  details?: string;
  establishYear?: string;
  historyDetails?: string;
  historyImageUrl?: string;
  id?: number;
  images?: Array<AboutImages>;
  missionAndValues?: Array<MissionAndValues>;
  shortTitle?: string;
  thumbnailUrl?: string;
  title?: string;
  universityName?: string;
  validFields?: boolean;
}
