/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcademicsPage {
  details?: string;
  id?: number;
  shortTitle?: string;
  thumbnailUrl?: string;
  title?: string;
  validFields?: boolean;
}
