/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Achievement {
  achievement?: string;
  details?: string;
  iconUrl?: string;
  id?: number;
}
