/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HtmlTable } from '../models/html-table';
export interface AdmissionInfo {
  id?: number;
  othersInfo?: Array<HtmlTable>;
  title?: string;
}
