/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdmissionInfo } from '../models/admission-info';
import { AdmissionRequirement } from '../models/admission-requirement';
export interface Admission {
  currentSession?: string;
  id?: number;
  othersInfo?: Array<AdmissionInfo>;
  requirements?: Array<AdmissionRequirement>;
  validFields?: boolean;
}
