/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DepartmentInfo } from '../models/department-info';
import { Faculty } from '../models/faculty';
export interface Department {
  aboutDepartment?: string;
  departmentInfo?: Array<DepartmentInfo>;
  details?: string;
  facultyList?: Array<Faculty>;
  id?: number;
  name?: string;
  shortTitle?: string;
  thumbnailUrl?: string;
  validFields?: boolean;
}
