/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HtmlTable } from '../models/html-table';
export interface DepartmentInfo {
  id?: number;
  infoName?: string;
  titles?: Array<HtmlTable>;
}
