/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Faculty {
  degree?: string;
  designation?: string;
  email?: string;
  ext?: string;
  faceBookProfileUrl?: string;
  id?: number;
  institution?: string;
  linkedInProfileUrl?: string;
  name?: string;
  phoneNumber?: string;
  profileImageUrl?: string;
  publication?: string;
  research?: string;
  roomNumber?: string;
  websiteUrl?: string;
}
