/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MenuLinks } from '../models/menu-links';
import { QuickButtons } from '../models/quick-buttons';
import { SocialMediaLinks } from '../models/social-media-links';
export interface Footer {
  copyrightText?: string;
  description?: string;
  fieldsValid?: boolean;
  id?: number;
  logoUrl?: string;
  menuLinks: Array<MenuLinks>;
  quickButtons: Array<QuickButtons>;
  socialMediaLinks: Array<SocialMediaLinks>;
}
