/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Menu } from '../models/menu';
import { MoreLink } from '../models/more-link';
export interface Header {
  id?: number;
  logoUrl: string;
  menus: Array<Menu>;
  moreLinks?: Array<MoreLink>;
  shortDetails: string;
  validFields?: boolean;
}
