/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Button } from '../models/button';
export interface Home {
  buttons?: Array<Button>;
  circle?: string;
  details: string;
  id?: number;
  imageOneUrl?: string;
  imageTwoUrl?: string;
  slogan: string;
  sloganIconUrl?: string;
  title: string;
  validFields?: boolean;
}
