/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TableData } from '../models/table-data';
export interface HtmlTable {
  details: Array<TableData>;
  id?: number;
  title?: string;
}
