/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MenuLinks {
  category?: string;
  id?: number;
  linkUrl?: string;
  menuName?: string;
}
