/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MissionAndValues {
  details?: string;
  id?: number;
  imageUrl?: string;
  title?: string;
}
