/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuickButtons {
  buttonColor?: string;
  buttonText?: string;
  id?: number;
  linkUrl?: string;
}
