/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Department } from '../models/department';
import { HtmlTable } from '../models/html-table';
import { Masters } from '../models/masters';
import { Undergraduate } from '../models/undergraduate';
export interface School {
  currentSession?: string;
  departments?: Array<Department>;
  details?: string;
  id?: number;
  masters?: Masters;
  thumbnailUrl?: string;
  title?: string;
  tuitionFee?: Array<HtmlTable>;
  undergraduate?: Undergraduate;
  validFields?: boolean;
}
