/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HtmlTable } from '../models/html-table';
export interface Scholarship {
  details?: Array<HtmlTable>;
  id?: number;
  title?: string;
  validFields?: boolean;
}
