/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SocialMediaLinks {
  iconClass?: string;
  iconUrl?: string;
  id?: number;
  linkUrl?: string;
  platform?: string;
}
