/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HtmlTable } from '../models/html-table';
export interface Undergraduate {
  details?: string;
  id?: number;
  info?: Array<HtmlTable>;
  title?: string;
}
