/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsersRequest {
  email?: string;
  password?: string;
  role?: string;
  username?: string;
}
