/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';
import { Operation, UrlPath } from '../fn/operations.class';
import { Home } from '../models';


@Injectable({ providedIn: 'root' })
export class HomeService extends BaseService {

  urlPaths: UrlPath = {
    get: '/api/v1/page/home/get',
    create: '/api/v1/page/home/add',
    update: '/api/v1/page/home/update',
    delete: '/api/v1/page/home/delete'
    
  };

  private operation: Operation = new Operation(this.urlPaths);

  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  getAllResponse(context?: HttpContext): Observable<StrictHttpResponse<{
  }>> {
      return this.operation.getAll(this.http, this.rootUrl, context);
    }
  
  
    getAll(context?: HttpContext): Observable<{
  }> {
      return this.getAllResponse(context).pipe(
        map((r: StrictHttpResponse<{
  }>): {
  } => r.body)
      );
    }

  
    getByIdResponse(id:string, context?: HttpContext): Observable<StrictHttpResponse<{
    }>> {
        return this.operation.getById(this.http, this.rootUrl, id, context);
      }
    
    
    getById(id:string, context?: HttpContext): Observable<{
    }> {
        return this.getByIdResponse(id,context).pipe(
          map((r: StrictHttpResponse<{
    }>): {
    } => r.body)
        );
      }

    createResponse(data: Home, context?: HttpContext): Observable<StrictHttpResponse<{
      }>> {
          return this.operation.create(this.http, this.rootUrl, data, context);
        }
      
      
    create(data: Home, context?: HttpContext): Observable<{
      }> {
          return this.createResponse(data,context).pipe(
            map((r: StrictHttpResponse<{
      }>): {
      } => r.body)
          );
        }

  updateResponse(data: Home, id: number, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return this.operation.update(this.http, this.rootUrl, data, id, context);
  }


  updateHome(data: Home, id: number, context?: HttpContext): Observable<{
}> {
    return this.updateResponse(data, id, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  deleteResponse(id:number, context?: HttpContext): Observable<StrictHttpResponse<{
  }>> {
      return this.operation.delete(this.http, this.rootUrl, id, context);
    }
  
  
  delete(id:number, context?: HttpContext): Observable<{
  }> {
      return this.deleteResponse(id,context).pipe(
        map((r: StrictHttpResponse<{
  }>): {
  } => r.body)
      );
    }

}
